# ===================================================================
# Порядок прокачки зданий для уровней Лорда 10-18
# Beast Lord Bot v3.0
#
# Структура:
# - lord_X - конфигурация для уровня Лорда X
# - buildings - список зданий в СТРОГОМ порядке прокачки
# - name - название здания (должно совпадать с OCR)
# - count - количество экземпляров (1 = уникальное, >1 = множественное)
# - target_level - целевой уровень для этого этапа
# - type - "unique" или "multiple"
# - action - "upgrade" (улучшить) или "build" (построить новое)
#
# ВАЖНО: После постройки нового здания с action="build" и target_level=1,
#        бот НЕ будет качать его дальше в рамках текущего lord_X.
#        Он перейдет к следующему зданию в списке.
# ===================================================================

lord_10:
  # Промежуточные здания перед Лордом 11
  buildings:
    - name: "Улей"
      count: 3
      target_level: 10
      type: "multiple"
      action: "upgrade"

    - name: "Ферма Грунта"
      count: 4
      target_level: 10
      type: "multiple"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 4
      target_level: 10
      type: "multiple"
      action: "upgrade"

    - name: "Куст"
      count: 4
      target_level: 10
      type: "multiple"
      action: "upgrade"

    - name: "Пруд"
      count: 4
      target_level: 8
      type: "multiple"
      action: "upgrade"

    - name: "Флора Эволюции"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Водохранилище"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Жилище Детенышей"
      count: 4
      target_level: 10
      type: "multiple"
      action: "upgrade"

    - name: "Логово Всеядных"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

lord_11:
  buildings:
    # ПЕРВОЕ здание ВСЕГДА Лорд
    - name: "Лорд"
      count: 1
      target_level: 11
      type: "unique"
      action: "upgrade"

    # Промежуточные здания перед Лордом 12
    - name: "Склад Песка"
      count: 1
      target_level: 8
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев"
      count: 1
      target_level: 8
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта"
      count: 1
      target_level: 8
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов"
      count: 1
      target_level: 8
      type: "unique"
      action: "upgrade"

    - name: "Флора Эволюции"
      count: 1
      target_level: 8
      type: "unique"
      action: "upgrade"

    - name: "Улей"
      count: 1
      target_level: 11
      type: "multiple"
      action: "upgrade"

    - name: "Ферма Грунта"
      count: 1
      target_level: 11
      type: "multiple"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 11
      type: "multiple"
      action: "upgrade"

    - name: "Жилище Детенышей"
      count: 4
      target_level: 11
      type: "multiple"
      action: "upgrade"

    - name: "Логово Всеядных"
      count: 1
      target_level: 11
      type: "unique"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 11
      type: "unique"
      action: "upgrade"

    - name: "Центр Альянса"
      count: 1
      target_level: 11
      type: "unique"
      action: "upgrade"

lord_12:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 12
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка"
      count: 1
      target_level: 9
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев"
      count: 1
      target_level: 9
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта"
      count: 1
      target_level: 9
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов"
      count: 1
      target_level: 9
      type: "unique"
      action: "upgrade"

    - name: "Флора Эволюции"
      count: 1
      target_level: 9
      type: "unique"
      action: "upgrade"

    - name: "Улей"
      count: 1
      target_level: 12
      type: "multiple"
      action: "upgrade"

    - name: "Ферма Грунта"
      count: 1
      target_level: 12
      type: "multiple"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 12
      type: "multiple"
      action: "upgrade"

    - name: "Жилище Детенышей"
      count: 4
      target_level: 12
      type: "multiple"
      action: "upgrade"

    - name: "Логово Всеядных"
      count: 1
      target_level: 12
      type: "unique"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 12
      type: "unique"
      action: "upgrade"

    - name: "Центр Альянса"
      count: 1
      target_level: 12
      type: "unique"
      action: "upgrade"

lord_13:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 13
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

    - name: "Флора Эволюции"
      count: 1
      target_level: 10
      type: "unique"
      action: "upgrade"

    - name: "Улей"
      count: 1
      target_level: 13
      type: "multiple"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 13
      type: "multiple"
      action: "upgrade"

    - name: "Жилище Детенышей"
      count: 4
      target_level: 13
      type: "multiple"
      action: "upgrade"

    - name: "Логово Всеядных"
      count: 1
      target_level: 13
      type: "unique"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 13
      type: "unique"
      action: "upgrade"

    - name: "Центр Альянса"
      count: 1
      target_level: 13
      type: "unique"
      action: "upgrade"

    # ===============================================
    # НОВЫЕ ПОСТРОЙКИ (после завершения Лорда 13!)
    # Порядок важен: сначала Жилище Лемуров IV (4-й строитель)
    # ===============================================

    - name: "Жилище Лемуров IV"
      count: 1
      target_level: 1
      type: "unique"
      action: "build"
      note: "КРИТИЧНО: Открывает 4-й слот строителя! Строим первым."

    - name: "Центр Сбора II"
      count: 1
      target_level: 1
      type: "unique"
      action: "build"

    - name: "Склад Песка II"
      count: 1
      target_level: 2
      type: "unique"
      action: "build"
      note: "После постройки (level=1) сразу качаем до 2"

    - name: "Склад Листьев II"
      count: 1
      target_level: 2
      type: "unique"
      action: "build"

    - name: "Склад Грунта II"
      count: 1
      target_level: 2
      type: "unique"
      action: "build"

    - name: "Склад Фруктов II"
      count: 1
      target_level: 2
      type: "unique"
      action: "build"

lord_14:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 14
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка II"
      count: 1
      target_level: 3
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев II"
      count: 1
      target_level: 3
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта II"
      count: 1
      target_level: 3
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов II"
      count: 1
      target_level: 3
      type: "unique"
      action: "upgrade"

    - name: "Улей"
      count: 1
      target_level: 14
      type: "multiple"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 14
      type: "multiple"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 14
      type: "unique"
      action: "upgrade"

    - name: "Центр Альянса"
      count: 1
      target_level: 14
      type: "unique"
      action: "upgrade"

    # ===============================================
    # Жилище Детенышей:
    # 1. Строим 5-е жилище (с 0 до 1 уровня)
    # 2. Прокачиваем ВСЕ 5 жилищ до 14 (включая только что построенное)
    # ===============================================

    - name: "Жилище Детенышей"
      count: 5
      target_level: 1
      type: "multiple"
      action: "build"
      note: "Строим 5-е жилище (условие: Лорд >= 14)"

    - name: "Жилище Детенышей"
      count: 5
      target_level: 14
      type: "multiple"
      action: "upgrade"
      note: "Прокачиваем ВСЕ 5 жилищ до 14. Бот сначала прокачает 5-е (1→14), потом проверит остальные"

lord_15:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 15
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка II"
      count: 1
      target_level: 4
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев II"
      count: 1
      target_level: 4
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта II"
      count: 1
      target_level: 4
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов II"
      count: 1
      target_level: 4
      type: "unique"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 15
      type: "multiple"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 15
      type: "unique"
      action: "upgrade"

    # ===============================================
    # ТЕПЕРЬ качаем ВСЕ 5 жилищ!
    # Бот выберет жилище с минимальным уровнем (5-е, level=1)
    # ===============================================

    - name: "Жилище Детенышей"
      count: 5
      target_level: 15
      type: "multiple"
      action: "upgrade"
      note: "Качаем все 5 жилищ до 15. Бот сначала прокачает 5-е (level=1→15), потом остальные (14→15)"

    - name: "Центр Альянса"
      count: 1
      target_level: 15
      type: "unique"
      action: "upgrade"

lord_16:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 16
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка II"
      count: 1
      target_level: 5
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев II"
      count: 1
      target_level: 5
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта II"
      count: 1
      target_level: 5
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов II"
      count: 1
      target_level: 5
      type: "unique"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 16
      type: "multiple"
      action: "upgrade"

    - name: "Жилище Детенышей"
      count: 5
      target_level: 16
      type: "multiple"
      action: "upgrade"

    - name: "Логово Плотоядных"
      count: 1
      target_level: 16
      type: "unique"
      action: "upgrade"

lord_17:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 17
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка II"
      count: 1
      target_level: 6
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев II"
      count: 1
      target_level: 6
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта II"
      count: 1
      target_level: 6
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов II"
      count: 1
      target_level: 6
      type: "unique"
      action: "upgrade"

    - name: "Жилище Детенышей"
      count: 5
      target_level: 17
      type: "multiple"
      action: "upgrade"

    - name: "Фруктовый Сад"
      count: 1
      target_level: 17
      type: "multiple"
      action: "upgrade"

lord_18:
  buildings:
    - name: "Лорд"
      count: 1
      target_level: 18
      type: "unique"
      action: "upgrade"

    - name: "Склад Песка II"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Листьев II"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Грунта II"
      count: 1
      target_level: 7
      type: "unique"
      action: "upgrade"

    - name: "Склад Фруктов II"
      count: 1
      target_level: 6
      type: "unique"
      action: "upgrade"

    # ===============================================
    # ФИНАЛЬНАЯ ПОСТРОЙКА - Центр Сбора III
    # ===============================================

    - name: "Центр Сбора III"
      count: 1
      target_level: 1
      type: "unique"
      action: "build"
      note: "Финальное здание. После постройки строительство завершено!"

# ===================================================================
# КОНЕЦ КОНФИГУРАЦИИ
# После достижения 18 уровня Лорда и постройки Центра Сбора III
# строительство полностью завершено
# ===================================================================