emulator_settings:
  '0':
    paused: false
    squads:
      special:
        enabled: true
        wild_level: 11
      squad_1:
        enabled: true
        wild_level: 11
      squad_2:
        enabled: false
        wild_level: 1
      squad_3:
        enabled: false
        wild_level: 1
    wilds:
      resources:
        apples: true
        honey: false
        leaves: true
        sand: true
        soil: true
      use_sheet_2: false
  '1':
    squads:
      special:
        enabled: true
        wild_level: 12
      squad_1:
        enabled: true
        wild_level: 12
      squad_2:
        enabled: false
        wild_level: 1
      squad_3:
        enabled: false
        wild_level: 1
    wilds:
      resources:
        apples: false
        honey: false
        leaves: true
        sand: true
        soil: false
      use_sheet_2: false
  '5':
    paused: false
    squads:
      special:
        enabled: true
        wild_level: 13
      squad_1:
        enabled: true
        wild_level: 13
      squad_2:
        enabled: false
        wild_level: 1
      squad_3:
        enabled: false
        wild_level: 1
    tiles:
      max_level: 7
      min_level: 4
      resources:
        apples: true
        leaves: true
        sand: true
        soil: true
    wilds:
      resources:
        apples: true
        honey: false
        leaves: true
        sand: true
        soil: true
      use_sheet_2: true
emulators:
  enabled:
  - 5
functions:
  building: false
  coop: false
  feeding_zone: false
  mail_rewards: false
  ponds: false
  prime_times: false
  research: false
  shield: false
  tiles: false
  training: true
  wilds: false
settings:
  max_concurrent: 3
