emulator_settings:
  '0':
    paused: false
    squads:
      special:
        enabled: true
        wild_level: 9
      squad_1:
        enabled: true
        wild_level: 9
      squad_2:
        enabled: false
        wild_level: 1
      squad_3:
        enabled: false
        wild_level: 1
    wilds:
      use_sheet_2: false
  '1':
    squads:
      special:
        enabled: true
        wild_level: 11
      squad_1:
        enabled: true
        wild_level: 10
      squad_2:
        enabled: false
        wild_level: 1
      squad_3:
        enabled: false
        wild_level: 1
    wilds:
      resources:
        apples: true
        honey: true
        leaves: true
        sand: true
        soil: true
      use_sheet_2: false
  '5':
    paused: false
    squads:
      special:
        enabled: false
        wild_level: 1
      squad_1:
        enabled: true
        wild_level: 13
      squad_2:
        enabled: false
        wild_level: 1
      squad_3:
        enabled: false
        wild_level: 1
    wilds:
      use_sheet_2: false
emulators:
  enabled:
  - 5
functions:
  building: false
  coop: false
  feeding_zone: false
  mail_rewards: false
  ponds: false
  prime_times: false
  research: false
  shield: false
  tiles: false
  wilds: true
settings:
  max_concurrent: 3
